import { OfferItem, MenuItem, MenuCategory } from './types'

export const DEFAULT_OFFER: OfferItem[] = [
  { name: 'Kids Meal', price: 99 },
  { name: 'Couple Meal', price: 170 },
  { name: 'Dinner Meal', price: 299 },
]

export const DEFAULT_MENU: MenuCategory[] = [
  {
    slug: 'rolls',
    label: 'Rolls',
    type: 'veg',
    items: [
      { name: 'Paneer Roll', price: 75 },
      { name: 'Fried Roll', price: 80 },
      { name: 'Falafel Roll', price: 60 },
      { name: 'Sp. Falafel Roll', price: 80 },
      { name: 'Zinger Wrap', price: 120 },
      { name: 'Porotta Roll', price: 70 },
      { name: 'Beef Wrap Roll', price: 150, type: 'nonveg' },
    ],
  },
  {
    slug: 'loaded-fries',
    label: 'Loaded Fries',
    type: 'veg',
    items: [
      { name: 'Loaded Fries Normal H/F', price: 150 },
      { name: 'Loaded Fries Cheese', price: 200 },
      { name: 'Peri Peri Loaded', price: 220 },
      { name: 'Special Loaded', price: 240 },
    ],
  },
  {
    slug: 'chicken',
    label: 'Chicken',
    type: 'nonveg',
    items: [
      { name: 'Special Fried 1 Pcs', price: 140 },
      { name: 'Chicken Lolly Pop', price: 160 },
      { name: 'Peri Peri Dynamic', price: 180 },
      { name: 'Shezwan Wings', price: 160 },
      { name: 'Chicken Nuggets', price: 140 },
      { name: 'Chicken Strip', price: 160 },
      { name: 'Pop Chick', price: 130 },
      { name: 'Chicken Wings Normal', price: 140 },
    ],
  },
  {
    slug: 'maggi',
    label: 'Maggi',
    type: 'veg',
    items: [
      { name: 'Maggi', price: 60 },
      { name: 'Maggi Special', price: 90 },
      { name: 'Cheese Maggi', price: 140 },
    ],
  },
  {
    slug: 'sandwich',
    label: 'Sandwich',
    type: 'veg',
    items: [
      { name: 'Normal Sandwich', price: 99 },
      { name: 'Club Special Sandwich', price: 220 },
    ],
  },
  {
    slug: 'pasta',
    label: 'Pasta',
    type: 'veg',
    items: [
      { name: 'Pasta', price: 210 },
      { name: 'Pasta Special', price: 260 },
    ],
  },
  {
    slug: 'pizza',
    label: 'Pizza',
    type: 'veg',
    items: [
      { name: 'Normal Pizza', price: 230 },
      { name: 'Peri Peri Pizza', price: 250 },
      { name: 'BBQ Pizza', price: 249 },
      { name: 'Paneer Pizza', price: 220 },
      { name: 'Mushroom Pizza', price: 230 },
    ],
  },
  {
    slug: 'momos',
    label: 'Momos',
    type: 'nonveg',
    items: [
      { name: 'CH Steam Momos', price: 160 },
      { name: 'Shezwan Momos', price: 180 },
      { name: 'Fried Momos', price: 160 },
    ],
  },
  {
    slug: 'burger',
    label: 'Burger',
    type: 'mixed',
    items: [
      { name: 'Chicken Burger', price: 90, type: 'nonveg' },
      { name: 'Crispy Double Burger', price: 189, type: 'nonveg' },
      { name: 'Veg Burger', price: 80, type: 'veg' },
      { name: 'Zinger Burger', price: 120, type: 'nonveg' },
      { name: 'Kids Burger', price: 60, type: 'nonveg' },
      { name: 'Aloo Tikka Burger', price: 100, type: 'veg' },
      { name: 'Falafel Burger', price: 70, type: 'veg' },
    ],
  },
  {
    slug: 'fresh-cream',
    label: 'Fresh Cream',
    type: 'veg',
    items: [
      { name: 'Custard Cream', price: 190 },
      { name: 'Apple Cream', price: 190 },
      { name: 'Dry Fruit Cream', price: 210 },
      { name: 'Mango Cream', price: 190 },
      { name: 'Berry Mix Cream', price: 240 },
      { name: 'Mixed Fruit Cream', price: 220 },
      { name: 'Fruit With Choco', price: 135 },
    ],
  },
  {
    slug: 'falooda',
    label: 'Falooda',
    type: 'veg',
    items: [
      { name: 'Dry Fruit Falooda', price: 180 },
      { name: 'Normal Falooda', price: 120 },
      { name: 'Royal Falooda', price: 140 },
      { name: 'Special Falooda', price: 180 },
      { name: 'Chocolate Falooda', price: 180 },
      { name: 'Fruit Salad', price: 70 },
      { name: 'Cut Fruit With Honey', price: 70 },
      { name: 'Butter Fruit With Honey', price: 100 },
    ],
  },
  {
    slug: 'ice-cream',
    label: 'Ice Cream',
    type: 'veg',
    items: [
      { name: 'Scoop', price: 40 },
      { name: 'Special Scoop', price: 90 },
      { name: 'Cake With Ice Cream', price: 160 },
    ],
  },
  {
    slug: 'mojito',
    label: 'Mojito',
    type: 'veg',
    items: [
      { name: 'Blueberry', price: 80 },
      { name: 'Strawberry', price: 80 },
      { name: 'Green Apple', price: 80 },
      { name: 'Passion Fruit', price: 80 },
      { name: 'Blue Curacao', price: 80 },
      { name: 'Mint', price: 80 },
      { name: 'Watermelon', price: 80 },
      { name: 'Mango', price: 80 },
    ],
  },
  {
    slug: 'lemon',
    label: 'Lemon',
    type: 'veg',
    items: [
      { name: 'Fresh Lime', price: 20 },
      { name: 'Mint Lemon', price: 25 },
      { name: 'Passion Fruit Lime', price: 30 },
      { name: 'Green Apple Lime', price: 30 },
      { name: 'Flavors Lime', price: 30 },
    ],
  },
  {
    slug: 'avil-milk',
    label: 'Avil Milk',
    type: 'veg',
    items: [
      { name: 'Avil Milk', price: 70 },
      { name: 'Avil Milk With Dry Fruits', price: 90 },
      { name: 'Avil Milk Special', price: 110 },
    ],
  },
  {
    slug: 'shake',
    label: 'Shake',
    type: 'veg',
    items: [
      { name: 'Chickoo', price: 60 },
      { name: 'Sharjah', price: 60 },
      { name: 'Apple', price: 80 },
      { name: 'Anar', price: 80 },
      { name: 'Cocktail', price: 60 },
      { name: 'Butter', price: 80 },
      { name: 'Tender Coconut', price: 70 },
      { name: 'Ice Cream Shake', price: 80 },
      { name: 'Mango', price: 70 },
      { name: 'Dry Fruits', price: 90 },
      { name: 'Dates & Roasted Cashew', price: 120 },
      { name: 'Custard Apple', price: 70 },
      { name: 'Blueberry', price: 100 },
      { name: 'Strawberry', price: 90 },
      { name: 'Berry Mix', price: 120 },
      { name: 'Galaxy Shake', price: 80 },
      { name: 'Oreo', price: 70 },
      { name: 'KitKat', price: 80 },
      { name: 'Gems', price: 80 },
      { name: 'Dragon Fruit', price: 90 },
    ],
  },
  {
    slug: 'shake-tender',
    label: 'Shake & Tender',
    type: 'veg',
    items: [
      { name: 'Cashew With Tender', price: 90 },
      { name: 'Dry Fruits With Tender', price: 100 },
      { name: 'Boost With Tender', price: 80 },
      { name: 'Dates With Tender', price: 90 },
      { name: 'Tender Coconut Special Shake', price: 70 },
      { name: 'Badam With Tender', price: 90 },
    ],
  },
  {
    slug: 'juice',
    label: 'Juice',
    type: 'veg',
    items: [
      { name: 'Orange', price: 60 },
      { name: 'Musambi', price: 60 },
      { name: 'Papaya', price: 60 },
      { name: 'Grape', price: 60 },
      { name: 'Anar', price: 60 },
      { name: 'Watermelon', price: 60 },
      { name: 'Pineapple', price: 60 },
      { name: 'Mango', price: 60 },
    ],
  },
  {
    slug: 'hot-drinks',
    label: 'Hot Drinks',
    type: 'veg',
    items: [
      { name: 'Coffee', price: 15 },
      { name: 'SP Coffee', price: 30 },
      { name: 'Tea', price: 15 },
      { name: 'Lemon Tea', price: 15 },
      { name: 'Boost', price: 20 },
      { name: 'Horlicks', price: 20 },
      { name: 'Badam Milk', price: 25 },
    ],
  },
]
